// theme.ts
export const theme = {
  colors: {
    primary: '#171717',
    secondary: '#4BB2FF',
    subpointRed: '#EF444D',
    subpointGreen: '#69D441',
    subpointPink: '#FF89E1',
    background: '#FFFFFF',
    text: '#333333',
    disabled: '#F6F6F6',
    gray: '#6A6C5E',
    black: '#000000',
    white: '#FFFFFF',
    lightest: '#FFF8E6',
  },
  scale: {
    gray: {
      gray1: '#212121',
      gray2: '#424242',
      gray3: '#616161',
      gray4: '#757575',
      gray5: '#9E9E9E',
      gray6: '#BDBDBD',
      gray7: '#E0E0E0',
      gray8: '#EEEEEE',
      gray9: '#F5F5F5',
      gray10: '#FAFAFA',
      gray11: '#FFFFFF',
    },
  },
  spacing: {
    xss: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 20,
    full: 999,
  },
  fontSize: {
    xxs: 10,
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 28,
  },
  fontFamily: {
    regular: 'Pretendard-Regular',
    medium: 'Pretendard-Medium',
    bold: 'Pretendard-Bold',
    black: 'Pretendard-Black',
    light: 'Pretendard-Light',
    thin: 'Pretendard-Thin',
    extraLight: 'Pretendard-ExtraLight',
    extraBold: 'Pretendard-ExtraBold',
    semiBold: 'Pretendard-SemiBold',
  },
};
